import type { Tournament, ShogiClass } from "./types";

/**
 * 見本データ（シード）
 *
 * 自動収集がまだ十分に集まっていないときでも、サイトがにぎやかに見えるように
 * 全国の「実在する有名なこども将棋大会」や「将棋教室の例」を入れている。
 *
 * ⚠️ 日程・会場は「例」です。必ず各主催の公式ページで最新情報を確認してください。
 *    （サイト全体にも同じ注意書きを大きく出している）
 */

type SeedTournament = Omit<Tournament, "status">;

export const SEED_TOURNAMENTS: SeedTournament[] = [
  {
    id: "t-monka-tokyo",
    title: "文部科学大臣杯 小・中学校将棋団体戦（東京都大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "東京都",
    city: "千代田区",
    venue: "未定（公式で発表）",
    eventDate: "2026-06-21",
    entryDeadline: "2026-06-07",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小学生・中学生（3人1チームの団体戦）",
    fee: "無料〜数百円程度",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "1チーム3人で戦う団体戦。各都道府県の代表が全国大会に進みます。学校のお友だちとチームを組んで参加できます。※日程は例です。公式ページで必ず確認してください。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-shogakusei-meijin",
    title: "小学生将棋名人戦（全国大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "東京都",
    city: "渋谷区",
    venue: "将棋会館ほか",
    eventDate: "2026-08-09",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（学年別の予選あり）",
    fee: "地区予選により異なる",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "小学生の日本一を決める大会。各地で地区予選が行われ、勝ち抜くと全国大会に出られます。テレビで放送されることもある大きな大会です。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-chugakusei-osho",
    title: "中学生将棋王将戦（全国大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "大阪府",
    city: "大阪市",
    venue: "関西将棋会館ほか",
    eventDate: "2026-08-16",
    ageGroups: ["junior"],
    gradeDetail: "中学生",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "中学生の日本一を決める大会。地区予選を勝ち抜いた代表が全国大会で対戦します。※日程は例です。公式ページで確認してください。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-kurashiki-osho",
    title: "倉敷王将戦（全国小学生将棋大会）",
    organizer: "倉敷市・日本将棋連盟",
    organizerType: "jsa",
    prefecture: "岡山県",
    city: "倉敷市",
    venue: "倉敷市内会場",
    eventDate: "2026-08-23",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "岡山県倉敷市で開かれる、小学生の全国大会。低学年・高学年に分かれて戦います。各地の予選を勝ち抜いて参加します。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-jt-cup-tokyo",
    title: "JT将棋日本シリーズ テーブルマークこども大会（東京会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "東京都",
    city: "江東区",
    venue: "東京ビッグサイトほか",
    eventDate: "2026-09-23",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description:
      "プロの公式戦と同じ日に開かれる、小学生向けの大きな大会。全国各地の会場で行われ、参加賞ももらえます。初めての子にもおすすめ。※日程は例です。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-jt-cup-osaka",
    title: "JT将棋日本シリーズ テーブルマークこども大会（大阪会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "大阪府",
    city: "大阪市",
    venue: "大阪市内会場",
    eventDate: "2026-10-04",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description:
      "西日本の小学生向け大会。たくさんの子が集まる、にぎやかなイベントです。※日程は例です。公式ページで確認してください。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-koukou-senshuken",
    title: "全国高等学校将棋選手権大会",
    organizer: "全国高等学校文化連盟・日本将棋連盟",
    organizerType: "jsa",
    prefecture: "東京都",
    city: "千代田区",
    venue: "全国大会会場",
    eventDate: "2026-07-25",
    endDate: "2026-07-27",
    ageGroups: ["high"],
    gradeDetail: "高校生（男子・女子）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "高校生の日本一を決める大会。各都道府県の予選を勝ち抜いた代表が集まります。団体戦・個人戦があります。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-sapporo-kodomo",
    title: "札幌こども将棋大会",
    organizer: "札幌市将棋連盟",
    organizerType: "municipal",
    prefecture: "北海道",
    city: "札幌市",
    venue: "市内公共施設",
    eventDate: "2026-06-14",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小学生・中学生（級位別クラスあり）",
    fee: "500円程度",
    description:
      "北海道の子ども向け地域大会。初心者から有段者までクラス分けがあるので、はじめてでも安心して参加できます。※日程は例です。地元の主催にご確認ください。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-sendai-kodomo",
    title: "仙台こども将棋まつり",
    organizer: "宮城県将棋会",
    organizerType: "municipal",
    prefecture: "宮城県",
    city: "仙台市",
    venue: "市民会館",
    eventDate: "2026-07-12",
    ageGroups: ["elementary", "junior"],
    fee: "無料",
    description:
      "東北地方の子ども将棋イベント。対局のほか、プロ棋士の指導対局コーナーもある楽しいおまつりです。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-nagoya-kodomo",
    title: "名古屋こども将棋大会",
    organizer: "愛知県将棋連盟",
    organizerType: "municipal",
    prefecture: "愛知県",
    city: "名古屋市",
    venue: "市内会場",
    eventDate: "2026-06-28",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小・中学生（クラス別）",
    fee: "500〜1000円",
    description:
      "中部地方の子ども向け大会。たくさんのクラスに分かれていて、自分の強さに合った相手と対局できます。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-fukuoka-kodomo",
    title: "福岡こどもしょうぎフェスタ",
    organizer: "福岡県将棋連盟",
    organizerType: "municipal",
    prefecture: "福岡県",
    city: "福岡市",
    venue: "市内ホール",
    eventDate: "2026-09-13",
    ageGroups: ["elementary", "junior", "high"],
    fee: "無料",
    description:
      "九州地方の大きな将棋イベント。小学生から高校生まで参加でき、駒の動かし方教室もあります。はじめての子も大かんげい。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-hiroshima-kodomo",
    title: "広島県こども将棋選手権",
    organizer: "広島県将棋連盟",
    organizerType: "municipal",
    prefecture: "広島県",
    city: "広島市",
    venue: "県立施設",
    eventDate: "2026-08-02",
    ageGroups: ["elementary", "junior"],
    fee: "500円",
    description:
      "中国地方の子ども選手権。勝ち進むと表彰されます。実力に合わせたクラス分けがあります。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-jt-cup-nagoya",
    title: "JT将棋日本シリーズ テーブルマークこども大会（名古屋会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "愛知県",
    city: "名古屋市",
    venue: "名古屋市内会場",
    eventDate: "2026-08-30",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description:
      "中部地方の小学生向け大会。全国各地の会場のひとつ。参加賞ももらえます。※日程は例です。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-jt-cup-sendai",
    title: "JT将棋日本シリーズ テーブルマークこども大会（仙台会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "宮城県",
    city: "仙台市",
    venue: "仙台市内会場",
    eventDate: "2026-09-06",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description: "東北地方の小学生向け大会。はじめての子も気軽に参加できます。※日程は例です。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-jt-cup-fukuoka",
    title: "JT将棋日本シリーズ テーブルマークこども大会（福岡会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "福岡県",
    city: "福岡市",
    venue: "福岡市内会場",
    eventDate: "2026-10-18",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description: "九州地方の小学生向け大会。たくさんの友だちと対局できます。※日程は例です。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-monka-saitama",
    title: "文部科学大臣杯 小・中学校将棋団体戦（埼玉県大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "埼玉県",
    city: "さいたま市",
    venue: "県内会場",
    eventDate: "2026-06-27",
    entryDeadline: "2026-06-13",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小学生・中学生（3人1チームの団体戦）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "埼玉県の予選大会。勝ち抜いたチームが全国大会に進みます。学校のお友だちとチームを組んで参加できます。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-monka-kanagawa",
    title: "文部科学大臣杯 小・中学校将棋団体戦（神奈川県大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "神奈川県",
    city: "横浜市",
    venue: "県内会場",
    eventDate: "2026-06-20",
    entryDeadline: "2026-06-06",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小学生・中学生（3人1チームの団体戦）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description: "神奈川県の予選大会。チームで力を合わせて全国を目指そう。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-osho-chiba",
    title: "中学生将棋王将戦（千葉県予選）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "千葉県",
    city: "千葉市",
    venue: "県内会場",
    eventDate: "2026-07-05",
    ageGroups: ["junior"],
    gradeDetail: "中学生",
    officialUrl: "https://www.shogi.or.jp/event/",
    description: "千葉県の中学生予選。勝ち抜くと全国大会に出られます。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-shizuoka-kodomo",
    title: "静岡こども将棋大会",
    organizer: "静岡県将棋連盟",
    organizerType: "municipal",
    prefecture: "静岡県",
    city: "静岡市",
    venue: "市内会場",
    eventDate: "2026-07-19",
    ageGroups: ["elementary", "junior"],
    fee: "500円",
    description: "静岡県の子ども向け大会。クラス分けがあるので、はじめてでも安心。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-koukou-kyoto",
    title: "全国高等学校将棋選手権大会（京都府予選）",
    organizer: "京都府高等学校文化連盟・日本将棋連盟",
    organizerType: "jsa",
    prefecture: "京都府",
    city: "京都市",
    venue: "府内会場",
    eventDate: "2026-06-13",
    ageGroups: ["high"],
    gradeDetail: "高校生（男子・女子）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description: "京都府の高校生予選。勝ち抜くと全国大会に進みます。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-joshi-zenkoku",
    title: "全国小学生・中学生女子将棋大会",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "兵庫県",
    city: "神戸市",
    venue: "全国大会会場",
    eventDate: "2026-08-11",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "女子（小学生・中学生）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "女の子のための全国大会。同じ年ごろの女子どうしで対局できるので、初めてでも参加しやすい大会です。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-niigata-kodomo",
    title: "新潟こども将棋まつり",
    organizer: "新潟県将棋連盟",
    organizerType: "municipal",
    prefecture: "新潟県",
    city: "新潟市",
    venue: "市内会場",
    eventDate: "2026-09-20",
    ageGroups: ["elementary", "junior"],
    fee: "無料",
    description: "対局のほか、駒の動かし方教室もある楽しいおまつり。はじめての子も大かんげい。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-okinawa-kodomo",
    title: "沖縄こどもしょうぎ大会",
    organizer: "沖縄県将棋連盟",
    organizerType: "municipal",
    prefecture: "沖縄県",
    city: "那覇市",
    venue: "市内会場",
    eventDate: "2026-08-08",
    ageGroups: ["elementary", "junior"],
    fee: "300円",
    description: "南国・沖縄の子ども将棋大会。クラス別なので、自分の強さに合った相手と対局できます。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-kumamoto-kodomo",
    title: "熊本こども将棋選手権",
    organizer: "熊本県将棋連盟",
    organizerType: "municipal",
    prefecture: "熊本県",
    city: "熊本市",
    venue: "市内会場",
    eventDate: "2026-07-26",
    ageGroups: ["elementary", "junior"],
    fee: "500円",
    description: "熊本県の子ども選手権。勝ち進むと表彰されます。※日程は例です。",
    sourceName: "地域大会（例）",
  },
];

export const SEED_CLASSES: ShogiClass[] = [
  {
    id: "c-tokyo-kaikan",
    name: "将棋会館 こども将棋教室",
    prefecture: "東京都",
    city: "渋谷区",
    schedule: "毎週土曜 10:00〜12:00",
    target: "幼児〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月3,000円程度",
    officialUrl: "https://www.shogi.or.jp/",
    description:
      "プロ棋士のいる将棋会館で開かれる教室。駒の動かし方から、強くなるコツまでていねいに教えてくれます。※内容は例です。公式でご確認ください。",
    sourceName: "日本将棋連盟（例）",
    sourceUrl: "https://www.shogi.or.jp/",
  },
  {
    id: "c-osaka-kaikan",
    name: "関西将棋会館 こども教室",
    prefecture: "大阪府",
    city: "大阪市",
    schedule: "毎週日曜 13:00〜15:00",
    target: "年長〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月3,000円程度",
    officialUrl: "https://www.shogi.or.jp/",
    description:
      "関西の将棋の中心地。レベルに合わせてクラス分けがあり、友だちもたくさんできます。※内容は例です。",
    sourceName: "日本将棋連盟（例）",
    sourceUrl: "https://www.shogi.or.jp/",
  },
  {
    id: "c-sapporo",
    name: "さっぽろ将棋スクール",
    prefecture: "北海道",
    city: "札幌市",
    schedule: "毎週土曜 9:30〜11:30",
    target: "5歳〜高校生",
    ageGroups: ["elementary", "junior", "high"],
    fee: "月2,500円",
    description:
      "はじめての子から大会をめざす子まで通える教室。先生がやさしく教えてくれます。※内容は例です。お近くの教室にご確認ください。",
    sourceName: "教室（例）",
  },
  {
    id: "c-nagoya",
    name: "名古屋こども将棋道場",
    prefecture: "愛知県",
    city: "名古屋市",
    schedule: "水曜・土曜 16:00〜18:00",
    target: "小学生・中学生",
    ageGroups: ["elementary", "junior"],
    fee: "1回500円",
    description:
      "平日にも通える道場。学校帰りに寄って、たくさん対局して強くなれます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-fukuoka",
    name: "福岡キッズしょうぎ教室",
    prefecture: "福岡県",
    city: "福岡市",
    schedule: "毎週日曜 10:00〜12:00",
    target: "年中〜小学生",
    ageGroups: ["elementary"],
    fee: "月2,800円",
    description:
      "小さな子向けにやさしく教える教室。駒の名前を覚えるところから始められます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-sendai",
    name: "仙台ジュニア将棋クラブ",
    prefecture: "宮城県",
    city: "仙台市",
    schedule: "毎週土曜 13:30〜15:30",
    target: "小学生〜高校生",
    ageGroups: ["elementary", "junior", "high"],
    fee: "月3,000円",
    description:
      "対局中心で、実戦の力がつく教室。大会に出たい子のサポートもしています。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-hiroshima",
    name: "広島こども将棋ひろば",
    prefecture: "広島県",
    city: "広島市",
    schedule: "毎週日曜 10:00〜12:00",
    target: "幼児〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月2,500円",
    description:
      "地域の子が集まる、あたたかい雰囲気の教室。はじめての子もすぐになじめます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-yokohama",
    name: "横浜こども将棋クラブ",
    prefecture: "神奈川県",
    city: "横浜市",
    schedule: "毎週土曜 14:00〜16:00",
    target: "小学生・中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月3,200円",
    description:
      "関東の人気教室。クラス別でていねいに教えてくれます。大会経験のある先生がいます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-kyoto",
    name: "京都こども将棋教室",
    prefecture: "京都府",
    city: "京都市",
    schedule: "毎週土曜 10:00〜12:00",
    target: "年長〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月2,800円",
    description: "落ち着いた雰囲気の教室。礼儀から学べます。はじめての子もていねいに教えてもらえます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-kobe",
    name: "神戸ジュニア将棋クラブ",
    prefecture: "兵庫県",
    city: "神戸市",
    schedule: "毎週日曜 13:00〜15:00",
    target: "小学生〜高校生",
    ageGroups: ["elementary", "junior", "high"],
    fee: "月3,000円",
    description: "対局中心で実戦の力がつくクラブ。大会を目指す子のサポートもしています。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-saitama",
    name: "さいたま将棋スクール",
    prefecture: "埼玉県",
    city: "さいたま市",
    schedule: "水曜・土曜 16:30〜18:30",
    target: "5歳〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "1回600円",
    description: "平日も通えるスクール。学校帰りに寄って、たくさん対局して強くなれます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-chiba",
    name: "千葉こども将棋道場",
    prefecture: "千葉県",
    city: "千葉市",
    schedule: "毎週土曜 14:00〜16:00",
    target: "幼児〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月2,500円",
    description: "あたたかい雰囲気の道場。駒の名前を覚えるところから始められます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-niigata",
    name: "新潟将棋こどもクラブ",
    prefecture: "新潟県",
    city: "新潟市",
    schedule: "毎週日曜 10:00〜12:00",
    target: "年中〜小学生",
    ageGroups: ["elementary"],
    fee: "月2,500円",
    description: "小さな子向けにやさしく教えるクラブ。みんなで楽しく将棋を覚えられます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-shizuoka",
    name: "静岡こども将棋教室",
    prefecture: "静岡県",
    city: "静岡市",
    schedule: "毎週土曜 9:30〜11:30",
    target: "小学生・中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月2,800円",
    description: "実力に合わせたクラス分けでていねいに教えてくれます。大会の練習にもなります。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-okinawa",
    name: "沖縄キッズ将棋クラブ",
    prefecture: "沖縄県",
    city: "那覇市",
    schedule: "毎週日曜 14:00〜16:00",
    target: "5歳〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月2,300円",
    description: "南国・沖縄の子ども将棋クラブ。はじめての子も大かんげい。※内容は例です。",
    sourceName: "教室（例）",
  },
];
