import type { Tournament, ShogiClass } from "./types";

/**
 * 見本データ（シード）
 *
 * 自動収集がまだ十分に集まっていないときでも、サイトがにぎやかに見えるように
 * 全国の「実在する有名なこども将棋大会」や「将棋教室の例」を入れている。
 *
 * ⚠️ 日程・会場は「例」です。必ず各主催の公式ページで最新情報を確認してください。
 *    （サイト全体にも同じ注意書きを大きく出している）
 */

type SeedTournament = Omit<Tournament, "status">;

export const SEED_TOURNAMENTS: SeedTournament[] = [
  {
    id: "t-monka-tokyo",
    title: "文部科学大臣杯 小・中学校将棋団体戦（東京都大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "東京都",
    city: "千代田区",
    venue: "未定（公式で発表）",
    eventDate: "2026-06-21",
    entryDeadline: "2026-06-07",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小学生・中学生（3人1チームの団体戦）",
    fee: "無料〜数百円程度",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "1チーム3人で戦う団体戦。各都道府県の代表が全国大会に進みます。学校のお友だちとチームを組んで参加できます。※日程は例です。公式ページで必ず確認してください。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-shogakusei-meijin",
    title: "小学生将棋名人戦（全国大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "東京都",
    city: "渋谷区",
    venue: "将棋会館ほか",
    eventDate: "2026-08-09",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（学年別の予選あり）",
    fee: "地区予選により異なる",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "小学生の日本一を決める大会。各地で地区予選が行われ、勝ち抜くと全国大会に出られます。テレビで放送されることもある大きな大会です。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-chugakusei-osho",
    title: "中学生将棋王将戦（全国大会）",
    organizer: "日本将棋連盟",
    organizerType: "jsa",
    prefecture: "大阪府",
    city: "大阪市",
    venue: "関西将棋会館ほか",
    eventDate: "2026-08-16",
    ageGroups: ["junior"],
    gradeDetail: "中学生",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "中学生の日本一を決める大会。地区予選を勝ち抜いた代表が全国大会で対戦します。※日程は例です。公式ページで確認してください。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-kurashiki-osho",
    title: "倉敷王将戦（全国小学生将棋大会）",
    organizer: "倉敷市・日本将棋連盟",
    organizerType: "jsa",
    prefecture: "岡山県",
    city: "倉敷市",
    venue: "倉敷市内会場",
    eventDate: "2026-08-23",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "岡山県倉敷市で開かれる、小学生の全国大会。低学年・高学年に分かれて戦います。各地の予選を勝ち抜いて参加します。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-jt-cup-tokyo",
    title: "JT将棋日本シリーズ テーブルマークこども大会（東京会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "東京都",
    city: "江東区",
    venue: "東京ビッグサイトほか",
    eventDate: "2026-09-23",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description:
      "プロの公式戦と同じ日に開かれる、小学生向けの大きな大会。全国各地の会場で行われ、参加賞ももらえます。初めての子にもおすすめ。※日程は例です。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-jt-cup-osaka",
    title: "JT将棋日本シリーズ テーブルマークこども大会（大阪会場）",
    organizer: "日本たばこ産業（JT）",
    organizerType: "private",
    prefecture: "大阪府",
    city: "大阪市",
    venue: "大阪市内会場",
    eventDate: "2026-10-04",
    ageGroups: ["elementary"],
    gradeDetail: "小学生（低学年・高学年の部）",
    fee: "無料",
    officialUrl: "https://www.jti.co.jp/sports/shogi/",
    description:
      "西日本の小学生向け大会。たくさんの子が集まる、にぎやかなイベントです。※日程は例です。公式ページで確認してください。",
    sourceName: "JT将棋日本シリーズ",
    sourceUrl: "https://www.jti.co.jp/sports/shogi/",
  },
  {
    id: "t-koukou-senshuken",
    title: "全国高等学校将棋選手権大会",
    organizer: "全国高等学校文化連盟・日本将棋連盟",
    organizerType: "jsa",
    prefecture: "東京都",
    city: "千代田区",
    venue: "全国大会会場",
    eventDate: "2026-07-25",
    endDate: "2026-07-27",
    ageGroups: ["high"],
    gradeDetail: "高校生（男子・女子）",
    officialUrl: "https://www.shogi.or.jp/event/",
    description:
      "高校生の日本一を決める大会。各都道府県の予選を勝ち抜いた代表が集まります。団体戦・個人戦があります。※日程は例です。",
    sourceName: "日本将棋連盟",
    sourceUrl: "https://www.shogi.or.jp/event/",
  },
  {
    id: "t-sapporo-kodomo",
    title: "札幌こども将棋大会",
    organizer: "札幌市将棋連盟",
    organizerType: "municipal",
    prefecture: "北海道",
    city: "札幌市",
    venue: "市内公共施設",
    eventDate: "2026-06-14",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小学生・中学生（級位別クラスあり）",
    fee: "500円程度",
    description:
      "北海道の子ども向け地域大会。初心者から有段者までクラス分けがあるので、はじめてでも安心して参加できます。※日程は例です。地元の主催にご確認ください。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-sendai-kodomo",
    title: "仙台こども将棋まつり",
    organizer: "宮城県将棋会",
    organizerType: "municipal",
    prefecture: "宮城県",
    city: "仙台市",
    venue: "市民会館",
    eventDate: "2026-07-12",
    ageGroups: ["elementary", "junior"],
    fee: "無料",
    description:
      "東北地方の子ども将棋イベント。対局のほか、プロ棋士の指導対局コーナーもある楽しいおまつりです。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-nagoya-kodomo",
    title: "名古屋こども将棋大会",
    organizer: "愛知県将棋連盟",
    organizerType: "municipal",
    prefecture: "愛知県",
    city: "名古屋市",
    venue: "市内会場",
    eventDate: "2026-06-28",
    ageGroups: ["elementary", "junior"],
    gradeDetail: "小・中学生（クラス別）",
    fee: "500〜1000円",
    description:
      "中部地方の子ども向け大会。たくさんのクラスに分かれていて、自分の強さに合った相手と対局できます。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-fukuoka-kodomo",
    title: "福岡こどもしょうぎフェスタ",
    organizer: "福岡県将棋連盟",
    organizerType: "municipal",
    prefecture: "福岡県",
    city: "福岡市",
    venue: "市内ホール",
    eventDate: "2026-09-13",
    ageGroups: ["elementary", "junior", "high"],
    fee: "無料",
    description:
      "九州地方の大きな将棋イベント。小学生から高校生まで参加でき、駒の動かし方教室もあります。はじめての子も大かんげい。※日程は例です。",
    sourceName: "地域大会（例）",
  },
  {
    id: "t-hiroshima-kodomo",
    title: "広島県こども将棋選手権",
    organizer: "広島県将棋連盟",
    organizerType: "municipal",
    prefecture: "広島県",
    city: "広島市",
    venue: "県立施設",
    eventDate: "2026-08-02",
    ageGroups: ["elementary", "junior"],
    fee: "500円",
    description:
      "中国地方の子ども選手権。勝ち進むと表彰されます。実力に合わせたクラス分けがあります。※日程は例です。",
    sourceName: "地域大会（例）",
  },
];

export const SEED_CLASSES: ShogiClass[] = [
  {
    id: "c-tokyo-kaikan",
    name: "将棋会館 こども将棋教室",
    prefecture: "東京都",
    city: "渋谷区",
    schedule: "毎週土曜 10:00〜12:00",
    target: "幼児〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月3,000円程度",
    officialUrl: "https://www.shogi.or.jp/",
    description:
      "プロ棋士のいる将棋会館で開かれる教室。駒の動かし方から、強くなるコツまでていねいに教えてくれます。※内容は例です。公式でご確認ください。",
    sourceName: "日本将棋連盟（例）",
    sourceUrl: "https://www.shogi.or.jp/",
  },
  {
    id: "c-osaka-kaikan",
    name: "関西将棋会館 こども教室",
    prefecture: "大阪府",
    city: "大阪市",
    schedule: "毎週日曜 13:00〜15:00",
    target: "年長〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月3,000円程度",
    officialUrl: "https://www.shogi.or.jp/",
    description:
      "関西の将棋の中心地。レベルに合わせてクラス分けがあり、友だちもたくさんできます。※内容は例です。",
    sourceName: "日本将棋連盟（例）",
    sourceUrl: "https://www.shogi.or.jp/",
  },
  {
    id: "c-sapporo",
    name: "さっぽろ将棋スクール",
    prefecture: "北海道",
    city: "札幌市",
    schedule: "毎週土曜 9:30〜11:30",
    target: "5歳〜高校生",
    ageGroups: ["elementary", "junior", "high"],
    fee: "月2,500円",
    description:
      "はじめての子から大会をめざす子まで通える教室。先生がやさしく教えてくれます。※内容は例です。お近くの教室にご確認ください。",
    sourceName: "教室（例）",
  },
  {
    id: "c-nagoya",
    name: "名古屋こども将棋道場",
    prefecture: "愛知県",
    city: "名古屋市",
    schedule: "水曜・土曜 16:00〜18:00",
    target: "小学生・中学生",
    ageGroups: ["elementary", "junior"],
    fee: "1回500円",
    description:
      "平日にも通える道場。学校帰りに寄って、たくさん対局して強くなれます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-fukuoka",
    name: "福岡キッズしょうぎ教室",
    prefecture: "福岡県",
    city: "福岡市",
    schedule: "毎週日曜 10:00〜12:00",
    target: "年中〜小学生",
    ageGroups: ["elementary"],
    fee: "月2,800円",
    description:
      "小さな子向けにやさしく教える教室。駒の名前を覚えるところから始められます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-sendai",
    name: "仙台ジュニア将棋クラブ",
    prefecture: "宮城県",
    city: "仙台市",
    schedule: "毎週土曜 13:30〜15:30",
    target: "小学生〜高校生",
    ageGroups: ["elementary", "junior", "high"],
    fee: "月3,000円",
    description:
      "対局中心で、実戦の力がつく教室。大会に出たい子のサポートもしています。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-hiroshima",
    name: "広島こども将棋ひろば",
    prefecture: "広島県",
    city: "広島市",
    schedule: "毎週日曜 10:00〜12:00",
    target: "幼児〜中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月2,500円",
    description:
      "地域の子が集まる、あたたかい雰囲気の教室。はじめての子もすぐになじめます。※内容は例です。",
    sourceName: "教室（例）",
  },
  {
    id: "c-yokohama",
    name: "横浜こども将棋クラブ",
    prefecture: "神奈川県",
    city: "横浜市",
    schedule: "毎週土曜 14:00〜16:00",
    target: "小学生・中学生",
    ageGroups: ["elementary", "junior"],
    fee: "月3,200円",
    description:
      "関東の人気教室。クラス別でていねいに教えてくれます。大会経験のある先生がいます。※内容は例です。",
    sourceName: "教室（例）",
  },
];
